- name: MY_FIRST_TOPIC-to-MY_RESPONSE_TOPIC
  logLevel: 0 # 0 = DEBUG, 1 = INFO, 2 = WARN, 3 = ERROR
  eventListener:
    type: kafka
    topic: MY_FIRST_TOPIC # the topic from which events are consumed
    consumerConfig:
      bootstrap.servers: localhost, 127.0.0.1
      group.id: myVeryFirstGroup
      auto.offset.reset: earliest
      enable.auto.commit: false # auto commit should be disabled since the listener commits messages only if everything was fine
  eventHandler:
    type: http
    method: POST # the http method that is used for the request
    url: http://localhost:8080/payload # the URL to which the event is sent
    headers:
      Content-Type: application/text # defaults to application/text
      Authorization: Basic ...
  eventResultProcessor:
    type: kafka
    topic: MY_RESPONSE_TOPIC # the topic to which the response body received from the eventHandler is sent to
    when:
      - onSuccess # can be 'onSuccess' which means the response is published if HTTP statusCode < 400, or 'onError' for HTTP statusCode >= 400
    producerConfig:
      bootstrap.servers: localhost
      acks: all